### PR TITLE
 feat like and bookmark a post

### PR DESCRIPTION
**Pull request by hsnice16**
### This PR will add code for the Like and Bookmark feature of a post

In this PR, **448 additions 158 deletions** lines of code
- many files are just backend related
- many files contain only 5 to 6 lines of code change

### Please review this PR and give your feedback

---

#### [Live Preview](https://think-loud-git-functionality-post-hsnice16.vercel.app/home)

### CODE REVIEW

**Review by ApurvaSawant11 — APPROVED** [review]
Looks good to me! Great job with the UI as well. Great work

**Review by mikesch803 — APPROVED** [review]
you need also add liked posts  in the like tab of the profile page, apart from it, great work! nothing to suggest more.

**Comment by hsnice16** [comment]
> you need also add liked posts in the like tab of the profile page, apart from it, great work! nothing to suggest more.

Yup! will add.

**Comment by hsnice16** [comment]
Thankyou for reviewing,

**Pull request merged**
