### PR TITLE
add profile page and edit profile dialog

### PR DESCRIPTION
**Pull request by hsnice16**
### This PR will add code for the design of the Profile Page and Edit Profile dialog box.

In this PR, **454 additions and 20** lines of code
- some files are only for assets
- some files contain only 5 to 6 lines of code

### Please review this PR and give your feedback

---

#### [Live Preview](https://think-loud-git-page-profile-hsnice16.vercel.app/profile)

image
image

### CODE REVIEW

**Review by mikesch803 — APPROVED** [review]
I tried to change the name from the dialog box, it changed until I move to another page else The code is good, everything is well structured

**Review by MonikaJhingan — APPROVED** [review]
The code is very well implemented the UI looks good to be merged.

**Comment by hsnice16** [comment]
> I tried to change the name from the dialog box, it changed until I move to another page else The code is good, everything is well structured

Hey, thanks for reviewing. Yeah, I have not added the backend yet the PR was for design.

**Comment by hsnice16** [comment]
Thank you for reviewing,

**Pull request merged**
