### PR TITLE
 add sign up dialog and word count in broadcast dialog

### PR DESCRIPTION
**Pull request by hsnice16**
### This PR will add code for the Sign Up dialog and word count in text box

In this PR, **434 additions 136 deletions** lines of code
- some files contains only 5 to 6 lines of code

### Please review this PR and give your feedback

---

#### [Live Preview to check Broadcast Box](https://think-loud-git-page-authentication-hsnice16.vercel.app/home)

image

#### [Live Preview to check Sign Up Dialog](https://think-loud-git-page-authentication-hsnice16.vercel.app)

image

### CODE REVIEW

**Comment by sainath7878** [comment]
Screenshot 2022-05-08 at 10 22 06 AM

text should be ```By continuing,  you agree to Think Loud....``` I believe!

**Comment by hsnice16** [comment]
> Screenshot 2022-05-08 at 10 22 06 AM
> 
> text should be `By continuing, you agree to Think Loud....` I believe!

oh! thanks man

**Review by sainath7878 — APPROVED** [review]
Everything looks good. Great work on the broadcast dialog box and the word count!!

**Review by simran61 — APPROVED** [review]
Looks good
Nice UI !!

**Comment by hsnice16** [comment]
Thank you for reviewing,

**Pull request merged**
